//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class actionlist
    {
        public actionlist()
        {
            this.adminuserlogs = new HashSet<adminuserlog>();
            this.rolevsactions = new HashSet<rolevsaction>();
        }
    
        public int Id { get; set; }
        public string module_name { get; set; }
        public string controller_name { get; set; }
        public string action_name { get; set; }
        public string name_to_show { get; set; }
        public bool is_show_in_menu { get; set; }
        public int order_no { get; set; }
    
        public virtual ICollection<adminuserlog> adminuserlogs { get; set; }
        public virtual ICollection<rolevsaction> rolevsactions { get; set; }
    }
}
