//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminuser
    {
        public adminuser()
        {
            this.adminuserlogs = new HashSet<adminuserlog>();
        }
    
        public int Id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int type { get; set; }
        public string phoneno { get; set; }
    
        public virtual ICollection<adminuserlog> adminuserlogs { get; set; }
    }
}
