//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class areazone
    {
        public areazone()
        {
            this.companies = new HashSet<company>();
            this.settings = new HashSet<setting>();
        }
    
        public int Id { get; set; }
        public string zone_name { get; set; }
        public string off_set { get; set; }
        public string summer { get; set; }
        public string country_code { get; set; }
        public string cicode { get; set; }
        public string cicodesummer { get; set; }
    
        public virtual ICollection<company> companies { get; set; }
        public virtual ICollection<setting> settings { get; set; }
    }
}
