//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class assign_to_group
    {
        public long Id { get; set; }
        public long contact_Infoid { get; set; }
        public int contact_groupid { get; set; }
        public System.DateTime created_time { get; set; }
    
        public virtual contact_group contact_group { get; set; }
        public virtual contactinformation contactinformation { get; set; }
    }
}
