//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditor
    {
        public int Id { get; set; }
        public int companyid { get; set; }
        public long employeeid { get; set; }
        public int auditor_type { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public long managerid { get; set; }
    
        public virtual company company { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
