//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public bank()
        {
            this.money_transfer = new HashSet<money_transfer>();
            this.money_transfer1 = new HashSet<money_transfer>();
        }
    
        public int Id { get; set; }
        public string bank_name { get; set; }
        public string account_name { get; set; }
        public string account_number { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> currencyid { get; set; }
        public int account_type { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual ICollection<money_transfer> money_transfer { get; set; }
        public virtual ICollection<money_transfer> money_transfer1 { get; set; }
    }
}
