//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class chartofaccount
    {
        public chartofaccount()
        {
            this.voucher_details = new HashSet<voucher_details>();
            this.items = new HashSet<item>();
            this.items1 = new HashSet<item>();
            this.items2 = new HashSet<item>();
            this.purchase_transaction_details = new HashSet<purchase_transaction_details>();
        }
    
        public int Id { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<int> taxid { get; set; }
        public string acode { get; set; }
        public string aname { get; set; }
        public string description { get; set; }
        public bool showsnsashboard { get; set; }
        public bool showinexpenseclaims { get; set; }
        public bool iscostcenter { get; set; }
        public int Level { get; set; }
    
        public virtual lookup lookup { get; set; }
        public virtual company company { get; set; }
        public virtual ICollection<voucher_details> voucher_details { get; set; }
        public virtual ICollection<item> items { get; set; }
        public virtual ICollection<item> items1 { get; set; }
        public virtual ICollection<item> items2 { get; set; }
        public virtual ICollection<purchase_transaction_details> purchase_transaction_details { get; set; }
    }
}
