//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_visitors
    {
        public long Id { get; set; }
        public long userid { get; set; }
        public Nullable<int> companyid { get; set; }
        public System.DateTime visiting_time { get; set; }
        public string ip_address { get; set; }
    
        public virtual company company { get; set; }
        public virtual user user { get; set; }
    }
}
