//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class companydocument
    {
        public long Id { get; set; }
        public int companyid { get; set; }
        public string document_location { get; set; }
        public string document_original_name { get; set; }
        public int State { get; set; }
    
        public virtual company company { get; set; }
    }
}
