//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.chartofaccounts = new HashSet<chartofaccount>();
            this.contact_group = new HashSet<contact_group>();
            this.contactinformations = new HashSet<contactinformation>();
            this.company_visitors = new HashSet<company_visitors>();
            this.company_profiles = new HashSet<company_profiles>();
            this.companydocuments = new HashSet<companydocument>();
            this.employees = new HashSet<employee>();
            this.founders = new HashSet<founder>();
            this.roles = new HashSet<role>();
            this.settings = new HashSet<setting>();
            this.auditors = new HashSet<auditor>();
            this.finalcial_setting = new HashSet<finalcial_setting>();
            this.tax_settings = new HashSet<tax_settings>();
        }
    
        public int Id { get; set; }
        public string trading_name { get; set; }
        public string legal_name { get; set; }
        public string display_name { get; set; }
        public Nullable<int> industryid { get; set; }
        public int countryid { get; set; }
        public Nullable<int> languageid { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public Nullable<int> p_o_box { get; set; }
        public string email { get; set; }
        public string location { get; set; }
        public string web_site { get; set; }
        public Nullable<int> legal_entity_id { get; set; }
        public Nullable<int> time_zone_id { get; set; }
        public string logo_location { get; set; }
        public string seal_location { get; set; }
        public Nullable<int> complete_flag { get; set; }
        public Nullable<long> ContactInformations_Id { get; set; }
        public long userid { get; set; }
    
        public virtual ICollection<chartofaccount> chartofaccounts { get; set; }
        public virtual areazone areazone { get; set; }
        public virtual country country { get; set; }
        public virtual industry industry { get; set; }
        public virtual language language { get; set; }
        public virtual legal_entities legal_entities { get; set; }
        public virtual ICollection<contact_group> contact_group { get; set; }
        public virtual ICollection<contactinformation> contactinformations { get; set; }
        public virtual contactinformation contactinformation { get; set; }
        public virtual ICollection<company_visitors> company_visitors { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<company_profiles> company_profiles { get; set; }
        public virtual ICollection<companydocument> companydocuments { get; set; }
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<founder> founders { get; set; }
        public virtual ICollection<role> roles { get; set; }
        public virtual ICollection<setting> settings { get; set; }
        public virtual ICollection<auditor> auditors { get; set; }
        public virtual ICollection<finalcial_setting> finalcial_setting { get; set; }
        public virtual ICollection<tax_settings> tax_settings { get; set; }
    }
}
