//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_group
    {
        public contact_group()
        {
            this.assign_to_group = new HashSet<assign_to_group>();
        }
    
        public int Id { get; set; }
        public string group_name { get; set; }
        public int company_id { get; set; }
    
        public virtual ICollection<assign_to_group> assign_to_group { get; set; }
        public virtual company company { get; set; }
    }
}
