//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_detail
    {
        public long Id { get; set; }
        public Nullable<long> employee_profile_id { get; set; }
        public Nullable<int> company_profile_id { get; set; }
        public string field_name { get; set; }
        public string field_value_one { get; set; }
        public string field_value_two { get; set; }
        public string field_value_three { get; set; }
        public string field_url { get; set; }
    
        public virtual company_profiles company_profiles { get; set; }
        public virtual employee_profiles employee_profiles { get; set; }
    }
}
