//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactdetail
    {
        public long Id { get; set; }
        public long contactinfoid { get; set; }
        public string attention { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string stateregion { get; set; }
        public string zipecode { get; set; }
        public string country { get; set; }
        public string type { get; set; }
    
        public virtual contactinformation contactinformation { get; set; }
    }
}
