//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactinformation
    {
        public contactinformation()
        {
            this.assign_to_group = new HashSet<assign_to_group>();
            this.contactdetails = new HashSet<contactdetail>();
            this.Notes = new HashSet<Note>();
            this.people = new HashSet<person>();
            this.telephones = new HashSet<telephone>();
            this.telephones1 = new HashSet<telephone>();
            this.purchase_transaction = new HashSet<purchase_transaction>();
            this.companies = new HashSet<company>();
            this.users = new HashSet<user>();
        }
    
        public long Id { get; set; }
        public int CompanyId { get; set; }
        public string contactname { get; set; }
        public string accountnumber { get; set; }
        public long postaladdid { get; set; }
        public long physicaladdid { get; set; }
        public int contacttype { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime updatedate { get; set; }
        public long createby { get; set; }
        public long updateby { get; set; }
    
        public virtual ICollection<assign_to_group> assign_to_group { get; set; }
        public virtual ICollection<contactdetail> contactdetails { get; set; }
        public virtual company company { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<person> people { get; set; }
        public virtual ICollection<telephone> telephones { get; set; }
        public virtual ICollection<telephone> telephones1 { get; set; }
        public virtual ICollection<purchase_transaction> purchase_transaction { get; set; }
        public virtual ICollection<company> companies { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
