//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public currency()
        {
            this.banks = new HashSet<bank>();
            this.vouchers = new HashSet<voucher>();
            this.purchase_transaction = new HashSet<purchase_transaction>();
            this.finalcial_setting = new HashSet<finalcial_setting>();
            this.finalcial_setting1 = new HashSet<finalcial_setting>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string symbol { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<bank> banks { get; set; }
        public virtual ICollection<voucher> vouchers { get; set; }
        public virtual ICollection<purchase_transaction> purchase_transaction { get; set; }
        public virtual ICollection<finalcial_setting> finalcial_setting { get; set; }
        public virtual ICollection<finalcial_setting> finalcial_setting1 { get; set; }
    }
}
