//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class designation
    {
        public designation()
        {
            this.invitations = new HashSet<invitation>();
            this.employees = new HashSet<employee>();
        }
    
        public int Id { get; set; }
        public string designation_name { get; set; }
    
        public virtual ICollection<invitation> invitations { get; set; }
        public virtual ICollection<employee> employees { get; set; }
    }
}
