//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.voucher_documents = new HashSet<voucher_documents>();
            this.vouchers = new HashSet<voucher>();
            this.Projects = new HashSet<Project>();
            this.TaskManagers = new HashSet<TaskManager>();
            this.purchase_transaction = new HashSet<purchase_transaction>();
            this.purchase_transaction_documents = new HashSet<purchase_transaction_documents>();
            this.userinroles = new HashSet<userinrole>();
            this.auditors = new HashSet<auditor>();
            this.auditors1 = new HashSet<auditor>();
        }
    
        public long Id { get; set; }
        public long userid { get; set; }
        public int companyid { get; set; }
        public int designationid { get; set; }
        public int branchid { get; set; }
        public string signaturelocation { get; set; }
    
        public virtual ICollection<voucher_documents> voucher_documents { get; set; }
        public virtual ICollection<voucher> vouchers { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<TaskManager> TaskManagers { get; set; }
        public virtual ICollection<purchase_transaction> purchase_transaction { get; set; }
        public virtual ICollection<purchase_transaction_documents> purchase_transaction_documents { get; set; }
        public virtual company company { get; set; }
        public virtual designation designation { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<userinrole> userinroles { get; set; }
        public virtual ICollection<auditor> auditors { get; set; }
        public virtual ICollection<auditor> auditors1 { get; set; }
    }
}
