//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_profiles
    {
        public employee_profiles()
        {
            this.contact_detail = new HashSet<contact_detail>();
        }
    
        public long Id { get; set; }
        public string image_location { get; set; }
        public string job_title { get; set; }
        public string bio { get; set; }
        public int location { get; set; }
        public bool IsActive { get; set; }
        public long userid { get; set; }
    
        public virtual ICollection<contact_detail> contact_detail { get; set; }
        public virtual user user { get; set; }
    }
}
