//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class finalcial_setting
    {
        public finalcial_setting()
        {
            this.vouchers = new HashSet<voucher>();
        }
    
        public int Id { get; set; }
        public int founded_year { get; set; }
        public int companyid { get; set; }
        public int periodid { get; set; }
        public int currencyid { get; set; }
        public double capital { get; set; }
        public double paid_up_capital { get; set; }
        public double share_price { get; set; }
        public double total_shares { get; set; }
        public int shares_currencyid { get; set; }
        public bool is_active { get; set; }
        public System.DateTime starting_date { get; set; }
        public System.DateTime ending_date { get; set; }
        public Nullable<System.DateTime> period_lock_date { get; set; }
        public Nullable<System.DateTime> year_lock_date { get; set; }
    
        public virtual ICollection<voucher> vouchers { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual company company { get; set; }
    }
}
