//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class invitation
    {
        public long Id { get; set; }
        public string email { get; set; }
        public int companyid { get; set; }
        public int employee_type { get; set; }
        public int roleid { get; set; }
        public int designationid { get; set; }
        public string token { get; set; }
        public int status { get; set; }
        public System.DateTime send_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual designation designation { get; set; }
    }
}
