//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.purchase_transaction_details = new HashSet<purchase_transaction_details>();
        }
    
        public long Id { get; set; }
        public string item_name { get; set; }
        public string item_code { get; set; }
        public Nullable<int> asset_accountid { get; set; }
        public double purchase_unit_price { get; set; }
        public double quantity { get; set; }
        public Nullable<int> purchase_accountid { get; set; }
        public Nullable<int> purchase_tax_rateid { get; set; }
        public string purchase_description { get; set; }
        public double sell_unit_price { get; set; }
        public Nullable<int> sales_accountid { get; set; }
        public Nullable<int> sales_tax_rateid { get; set; }
        public string Sales_description { get; set; }
    
        public virtual chartofaccount chartofaccount { get; set; }
        public virtual chartofaccount chartofaccount1 { get; set; }
        public virtual chartofaccount chartofaccount2 { get; set; }
        public virtual lookup lookup { get; set; }
        public virtual lookup lookup1 { get; set; }
        public virtual ICollection<purchase_transaction_details> purchase_transaction_details { get; set; }
    }
}
