//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.companies = new HashSet<company>();
            this.founders = new HashSet<founder>();
        }
    
        public int Id { get; set; }
        public string language_name { get; set; }
        public string code { get; set; }
        public string code1 { get; set; }
        public string native { get; set; }
    
        public virtual ICollection<company> companies { get; set; }
        public virtual ICollection<founder> founders { get; set; }
    }
}
