//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class legal_entities
    {
        public legal_entities()
        {
            this.companies = new HashSet<company>();
        }
    
        public int Id { get; set; }
        public string legal_entity_name { get; set; }
    
        public virtual ICollection<company> companies { get; set; }
    }
}
