//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class money_transfer
    {
        public long Id { get; set; }
        public Nullable<int> from_bankid { get; set; }
        public Nullable<int> to_bankid { get; set; }
        public System.DateTime transfer_date { get; set; }
        public double amount { get; set; }
        public string referenceno { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual bank bank1 { get; set; }
    }
}
