//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public long Id { get; set; }
        public long ContactInfoId { get; set; }
        public long userid { get; set; }
        public string details { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual contactinformation contactinformation { get; set; }
        public virtual user user { get; set; }
    }
}
