//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.TaskManagers = new HashSet<TaskManager>();
        }
    
        public long Id { get; set; }
        public string project_name { get; set; }
        public long managerid { get; set; }
        public long companyid { get; set; }
        public System.DateTime project_date { get; set; }
        public Nullable<System.DateTime> starting_date { get; set; }
        public Nullable<System.DateTime> finishingDate { get; set; }
        public int status { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual ICollection<TaskManager> TaskManagers { get; set; }
    }
}
