//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_transaction
    {
        public purchase_transaction()
        {
            this.purchase_transaction_details = new HashSet<purchase_transaction_details>();
            this.purchase_transaction_documents = new HashSet<purchase_transaction_documents>();
        }
    
        public long Id { get; set; }
        public long contactid { get; set; }
        public long employeeid { get; set; }
        public int currencyid { get; set; }
        public System.DateTime transaction_date { get; set; }
        public System.DateTime delivery_date { get; set; }
        public string order_number { get; set; }
        public string referenceno { get; set; }
        public string po_delivery_instruction { get; set; }
        public string po_attention { get; set; }
        public string po_telephone { get; set; }
        public string po_address { get; set; }
        public int transaction_type { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual contactinformation contactinformation { get; set; }
        public virtual ICollection<purchase_transaction_details> purchase_transaction_details { get; set; }
        public virtual ICollection<purchase_transaction_documents> purchase_transaction_documents { get; set; }
        public virtual employee employee { get; set; }
    }
}
