//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_transaction_details
    {
        public long Id { get; set; }
        public long purchase_transactionid { get; set; }
        public long itemid { get; set; }
        public int coaid { get; set; }
        public int TaxOnTransaction { get; set; }
        public double quantity { get; set; }
        public double unit_price { get; set; }
        public double discount { get; set; }
        public int taxid { get; set; }
        public string description { get; set; }
    
        public virtual chartofaccount chartofaccount { get; set; }
        public virtual lookup lookup { get; set; }
        public virtual item item { get; set; }
        public virtual purchase_transaction purchase_transaction { get; set; }
    }
}
