//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_transaction_documents
    {
        public long Id { get; set; }
        public long purchase_transactionid { get; set; }
        public long employeeid { get; set; }
        public string document_type { get; set; }
        public string description { get; set; }
        public string file_location { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual purchase_transaction purchase_transaction { get; set; }
        public virtual employee employee { get; set; }
    }
}
