//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.rolevsactions = new HashSet<rolevsaction>();
            this.userinroles = new HashSet<userinrole>();
        }
    
        public int Id { get; set; }
        public string role_name { get; set; }
        public string remarks { get; set; }
        public int ccompanyid { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<rolevsaction> rolevsactions { get; set; }
        public virtual ICollection<userinrole> userinroles { get; set; }
    }
}
