//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public long Id { get; set; }
        public Nullable<int> companyid { get; set; }
        public long user_Id { get; set; }
        public bool lg_company { get; set; }
        public bool lg_dash { get; set; }
        public bool lg_last { get; set; }
        public Nullable<int> Time_zoneId { get; set; }
        public int State { get; set; }
    
        public virtual areazone areazone { get; set; }
        public virtual company company { get; set; }
        public virtual user user { get; set; }
    }
}
