//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class sharetransfer
    {
        public int Id { get; set; }
        public int fromfounderid { get; set; }
        public int tofounderid { get; set; }
        public int transferamount { get; set; }
        public double UnitShareValue { get; set; }
        public System.DateTime transfertime { get; set; }
    
        public virtual founder founder { get; set; }
        public virtual founder founder1 { get; set; }
    }
}
