//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskManager
    {
        public long Id { get; set; }
        public long employeeid { get; set; }
        public long projectid { get; set; }
        public string title { get; set; }
        public System.DateTime task_date { get; set; }
        public System.DateTime starting_date { get; set; }
        public Nullable<System.DateTime> finishing_Date { get; set; }
        public int status { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual employee employee { get; set; }
    }
}
