//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_settings
    {
        public int Id { get; set; }
        public string tax_basis { get; set; }
        public string taxid { get; set; }
        public string display_name { get; set; }
        public int companyid { get; set; }
        public int periodid { get; set; }
    
        public virtual company company { get; set; }
    }
}
