//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class telephone
    {
        public long Id { get; set; }
        public long contactinfoId { get; set; }
        public string cellphone { get; set; }
        public string mobile { get; set; }
        public string directdial { get; set; }
        public string fax { get; set; }
        public string skype { get; set; }
        public string webSite { get; set; }
        public Nullable<long> ContactInformation_Id { get; set; }
    
        public virtual contactinformation contactinformation { get; set; }
        public virtual contactinformation contactinformation1 { get; set; }
    }
}
