//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.contactinformations = new HashSet<contactinformation>();
            this.Notes = new HashSet<Note>();
            this.company_visitors = new HashSet<company_visitors>();
            this.companies = new HashSet<company>();
            this.employee_profiles = new HashSet<employee_profiles>();
            this.employees = new HashSet<employee>();
            this.settings = new HashSet<setting>();
        }
    
        public long Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string status { get; set; }
        public Nullable<long> ContactInformations_Id { get; set; }
    
        public virtual ICollection<contactinformation> contactinformations { get; set; }
        public virtual contactinformation contactinformation { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<company_visitors> company_visitors { get; set; }
        public virtual ICollection<company> companies { get; set; }
        public virtual ICollection<employee_profiles> employee_profiles { get; set; }
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<setting> settings { get; set; }
    }
}
