//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher
    {
        public voucher()
        {
            this.voucher_details = new HashSet<voucher_details>();
            this.voucher_documents = new HashSet<voucher_documents>();
        }
    
        public long Id { get; set; }
        public int financial_settingid { get; set; }
        public int voucher_typeid { get; set; }
        public int branchid { get; set; }
        public int currencyid { get; set; }
        public long employeeid { get; set; }
        public System.DateTime voucher_date { get; set; }
        public string voucherno { get; set; }
        public string refferenceno { get; set; }
        public string description { get; set; }
        public string chequeno { get; set; }
        public Nullable<System.DateTime> cheque_date { get; set; }
        public string billno { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public string challen_no { get; set; }
        public string orderno { get; set; }
        public short posted { get; set; }
        public short disbursed { get; set; }
        public bool df { get; set; }
    
        public virtual ICollection<voucher_details> voucher_details { get; set; }
        public virtual ICollection<voucher_documents> voucher_documents { get; set; }
        public virtual vouchertype vouchertype { get; set; }
        public virtual currency currency { get; set; }
        public virtual employee employee { get; set; }
        public virtual finalcial_setting finalcial_setting { get; set; }
    }
}
