//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher_details
    {
        public long Id { get; set; }
        public long voucherid { get; set; }
        public int coaid { get; set; }
        public decimal debit { get; set; }
        public decimal credit { get; set; }
        public decimal taxdr { get; set; }
        public decimal taxcr { get; set; }
        public string description { get; set; }
    
        public virtual chartofaccount chartofaccount { get; set; }
        public virtual voucher voucher { get; set; }
    }
}
