//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhasb.DAL.Data.Db_Diagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebDiagram : DbContext
    {
        public WebDiagram()
            : base("name=WebDiagram")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<chartofaccount> chartofaccounts { get; set; }
        public virtual DbSet<money_transfer> money_transfer { get; set; }
        public virtual DbSet<voucher_details> voucher_details { get; set; }
        public virtual DbSet<voucher_documents> voucher_documents { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
        public virtual DbSet<vouchertype> vouchertypes { get; set; }
        public virtual DbSet<adminuser> adminusers { get; set; }
        public virtual DbSet<adminuserlog> adminuserlogs { get; set; }
        public virtual DbSet<areazone> areazones { get; set; }
        public virtual DbSet<contact_detail> contact_detail { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<industry> industries { get; set; }
        public virtual DbSet<language> languages { get; set; }
        public virtual DbSet<legal_entities> legal_entities { get; set; }
        public virtual DbSet<lookup> lookups { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<subscription> subscriptions { get; set; }
        public virtual DbSet<assign_to_group> assign_to_group { get; set; }
        public virtual DbSet<contact_group> contact_group { get; set; }
        public virtual DbSet<contactdetail> contactdetails { get; set; }
        public virtual DbSet<contactinformation> contactinformations { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<telephone> telephones { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<TaskManager> TaskManagers { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<purchase_transaction> purchase_transaction { get; set; }
        public virtual DbSet<purchase_transaction_details> purchase_transaction_details { get; set; }
        public virtual DbSet<purchase_transaction_documents> purchase_transaction_documents { get; set; }
        public virtual DbSet<company_visitors> company_visitors { get; set; }
        public virtual DbSet<invitation> invitations { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<company_profiles> company_profiles { get; set; }
        public virtual DbSet<companydocument> companydocuments { get; set; }
        public virtual DbSet<designation> designations { get; set; }
        public virtual DbSet<employee_profiles> employee_profiles { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<founder> founders { get; set; }
        public virtual DbSet<sharetransfer> sharetransfers { get; set; }
        public virtual DbSet<actionlist> actionlists { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<rolevsaction> rolevsactions { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<userinrole> userinroles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<auditor> auditors { get; set; }
        public virtual DbSet<finalcial_setting> finalcial_setting { get; set; }
        public virtual DbSet<tax_settings> tax_settings { get; set; }
    }
}
